export declare const TAB_KEY: number;
export declare const ENTER_KEY: number;
export declare const ESCAPE_KEY: number;
export declare const LEFT_KEY: number;
export declare const UP_KEY: number;
export declare const RIGHT_KEY: number;
export declare const DOWN_KEY: number;
export declare const DELETE_KEY: number;
export declare const BACKSPACE_KEY: number;
